export * from './code-postal';
export * from './commune';
export * from './courriel';
export * from './localisation';
export * from './nom';
export * from './regle';
export * from './site-web';
export * from './telephone';
export * from './voie';
