import type { Adresse } from './adresse';
import type { FormationsLabels } from './formation-label';
import type { PrisesEnChargeSpecifiques } from './prise-en-charge-specifique';
import type { PublicsSpecifiquementAdresses } from './publics-specifiquement-adresses';
import type { Typologies } from './typologie';
import type { Localisation } from './localisation';
import type { Contact } from './contact';
import type { Presentation } from './presentation';
import type { Services } from './service';
import type { FraisACharge } from './frais-a-charge';
import type { Itinerances } from './itinerance';
import type { ModalitesAccompagnement } from './modalite-accompagnement';
import type { ModalitesAcces } from './modalite-acces';
import type { FicheAccesLibre } from './fiche-acces-libre';
import type { Url } from './url';
import type { Pivot } from './pivot';
import type { DispositifProgrammesNationaux } from './dispositif-programme-national';
import type { Horaires } from './horaires';
import type { Id } from './id';
import type { Nom } from './nom';

export type LieuMediationNumerique = {
  id: Id;
  pivot?: Pivot | undefined;
  nom: Nom;
  adresse: Adresse;
  localisation?: Localisation | undefined;
  typologies?: Typologies | undefined;
  contact?: Contact | undefined;
  horaires?: Horaires | undefined;
  presentation?: Presentation | undefined;
  source?: string | undefined;

  date_maj?: Date | undefined;
  services?: Services | undefined;
  publics_specifiquement_adresses?: PublicsSpecifiquementAdresses | undefined;
  prise_en_charge_specifique?: PrisesEnChargeSpecifiques | undefined;
  modalites_acces?: ModalitesAcces | undefined;
  frais_a_charge?: FraisACharge | undefined;
  itinerance?: Itinerances | undefined;
  dispositif_programmes_nationaux?: DispositifProgrammesNationaux | undefined;
  formations_labels?: FormationsLabels | undefined;
  autres_formations_labels?: string[] | undefined;
  modalites_accompagnement?: ModalitesAccompagnement | undefined;
  fiche_acces_libre?: FicheAccesLibre | undefined;
  prise_rdv?: Url | undefined;
};
