---
name: Release

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload build bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: |
            package.json
            lib

  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest
    needs:
      - build-and-upload

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle

      # Using a symbolic link because there is no base option to have a config path with semantic-release as of 2022-08-31
      - name: Link the semantic release config and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          ln -s .tooling/.semantic-release/.semantic-release.config.cjs release.config.cjs
          ln -s .tooling/.semantic-release/.npmignore .npmignore
          npx semantic-release
